language: python
python:
    - 2.7
    - 3.5
    - 3.6
install:
    - pip install zc.buildout
    - buildout
script:
    - bin/test -pvc
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
